Add missing TCC permissions
facebook/idb pull request #796
Opened 2022-09-06 19:43 UTC by tylervick

## Motivation

There have been several new user permissions introduced over the last couple of major iOS versions. This change adds the missing permissions that may be modified via existing TCC.db queries.

Notably, the "Health" permission is missing since it requires modification to a standalone `healthdb.sqlite` database. This will be implemented in a future PR.

The following permissions have been added:
- calendar
- biometrics (aka FaceID)
- media
- reminders
- motion
- siri
- speech
- userTracking

## Test Plan

- Run `idb approve -h`
- Verify the output contains added permissions:
```
usage: idb approve [-h] [--scheme SCHEME] [--udid UDID]
                       [--log {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [--json]
                       bundle_id
                       {photos,camera,contacts,url,location,notification,microphone,calendar,faceid,media,reminders,motion,siri,speech,user_tracking}
                       [{photos,camera,contacts,url,location,notification,microphone,calendar,faceid,media,reminders,motion,siri,speech,user_tracking} ...]
```

- Grant any/all of the introduced permissions for a valid bundle ID:
  - `idb approve com.example.app calendar`
- Verify the supplied permissions have been successfully granted for the bundle ID

- Revoke any/all of the introduced permissions for a valid bundle ID:
  - `idb revoke com.example.app calendar`
- Verify the supplied permissions have been successfully revoked for the bundle ID

## Related PRs

2023-01-18 21:07 UTC, grzmiel approved these changes

2023-01-19 18:23 UTC, grzmiel requested changes
You have to add those entries to RevokeRequest as well.

2023-01-19 18:23 UTC, grzmiel commented on idb/grpc/client.py
> +    Permission.CALENDAR: ApproveRequest.CALENDAR,
Those should be RevokeRequest

2023-01-19 18:23 UTC, grzmiel commented on proto/idb.proto
> +    CALENDAR = 7;
Add the same entries in the RevokeRequest below

2023-08-21 06:34 UTC, fleitman commented
Do you have any new about this PR?

2023-08-21 06:39 UTC, fleytman commented
Do you have any new about this PR?

2023-11-27 03:07 UTC, fleytman commented
These are very useful changes, what's stopping you from making a merge of changes at this point?

2026-05-08 16:10 UTC, closed without merging